#!/usr/bin/env bash
SEL=$(xsel -o)
T="$(/usr/local/bin/trans -e deepl -o /tmp/output -theme=none :en "$SEL")"  #echo "Translation:" "$T" >> /tmp/
ansi2html /tmp/output
zenity --text-info --title="Spanish to English" --filename=/tmp/output
