#!/usr/bin/env bash
VAR=$(date | md5sum)
rm /tmp/VAR
SEL=$(xsel -o)
T="$(/usr/local/bin/trans -s es -e deepl -o /tmp/$VAR -theme=none :en "$SEL")"  #echo$
ansi2html /tmp/output
zenity --text-info --title="English to Spanish" --filename=/tmp/$VAR

